"""
Prior Disclosure Service
Generate CBP voluntary disclosure documents pursuant to 19 U.S.C. § 1592(c)(4).
"""
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone, timedelta
from uuid import uuid4
from enum import Enum

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)


class ViolationType(str, Enum):
    NEGLIGENCE = "negligence"
    GROSS_NEGLIGENCE = "gross_negligence"
    FRAUD = "fraud"


class ViolationCategory(str, Enum):
    CLASSIFICATION = "classification"
    VALUATION = "valuation"
    COUNTRY_OF_ORIGIN = "country_of_origin"
    MARKING = "marking"
    ANTIDUMPING = "antidumping"
    FREE_TRADE = "free_trade"
    OTHER = "other"


# Prior Disclosure document template
DISCLOSURE_TEMPLATE = """
PRIOR DISCLOSURE PURSUANT TO 19 U.S.C. § 1592(c)(4)

Date: {date}
Reference: {reference_number}

TO: U.S. Customs and Border Protection
    Fines, Penalties, and Forfeitures Office
    
FROM: {importer_name}
      {importer_address}

RE: PRIOR DISCLOSURE - {violation_category}
    Entry Numbers: {entry_numbers}
    Port(s) of Entry: {ports}

================================================================================

I. INTRODUCTION

This document constitutes a prior disclosure pursuant to 19 U.S.C. § 1592(c)(4) and 
19 C.F.R. § 162.74. The disclosing party voluntarily brings to the attention of 
U.S. Customs and Border Protection ("CBP") the following violation(s) of the customs 
laws before, or without knowledge of, the commencement of a formal investigation.

II. DISCLOSING PARTY

Company Name: {importer_name}
Importer of Record Number: {ior_number}
Contact Person: {contact_name}
Contact Information: {contact_info}

III. NATURE OF VIOLATION

Violation Type: {violation_type_desc}
Violation Category: {violation_category}

Description:
{violation_description}

IV. AFFECTED ENTRIES

Number of Affected Entries: {entry_count}
Date Range: {date_range}
Port(s) of Entry: {ports}

Entry Numbers:
{entry_list}

V. CIRCUMSTANCES OF VIOLATION

{circumstances}

The violation was discovered during a routine post-entry audit conducted on {audit_date}.
{discovery_details}

VI. CORRECTIVE ACTIONS TAKEN

The following corrective actions have been implemented:
{corrective_actions}

VII. FINANCIAL SUMMARY

Total Revenue Loss to the Government:
- Unpaid/Underpaid Duties: ${duty_loss:,.2f}
- Estimated Interest: ${interest:,.2f}
- Total Duty + Interest: ${total_owed:,.2f}

Penalty Exposure (per 19 U.S.C. § 1592):
- Maximum Penalty ({violation_type}): ${max_penalty:,.2f}
- Mitigated Penalty (with disclosure): ${mitigated_penalty:,.2f}

VIII. TENDER OF DUTIES AND INTEREST

{importer_name} hereby tenders payment in the amount of ${tender_amount:,.2f}, 
representing the total duties owed plus applicable interest, as calculated above.

☐ Check enclosed
☐ ACH payment initiated
☐ Payment to follow under separate cover

IX. CERTIFICATIONS

The undersigned certifies that:

1. This disclosure is made before, or without knowledge of, the commencement of a 
   formal investigation by CBP;

2. The information provided herein is true, accurate, and complete to the best of 
   the disclosing party's knowledge;

3. All relevant documentation has been preserved and will be made available upon 
   request;

4. The disclosing party commits to full cooperation with CBP in resolving this matter.

X. REQUEST FOR MITIGATION

Pursuant to 19 C.F.R. § 162.74(c), {importer_name} respectfully requests that CBP 
consider the following mitigating factors in determining any penalty:

- This disclosure is timely and voluntary
- Full cooperation with the disclosure process
- Immediate corrective actions implemented
- {additional_mitigation}

XI. STATUTE OF LIMITATIONS

Oldest Entry Date: {oldest_entry}
Statute Expiration: {statute_expiration}
Days Remaining: {days_remaining}

================================================================================

Respectfully submitted,

_______________________________
Authorized Signature

_______________________________
Print Name and Title

_______________________________
Date

================================================================================

ATTACHMENTS:
{attachments}

================================================================================
This document was generated by DocuMind AI Trade Compliance Module
Generated: {generated_at}
================================================================================
"""


def get_violation_description(violation_type: ViolationType) -> str:
    """Get legal description of violation type."""
    descriptions = {
        ViolationType.NEGLIGENCE: "Negligence - Failure to exercise reasonable care and competence to ensure that statements made and information provided are true and accurate (19 U.S.C. § 1592(a)(1)(A)(i))",
        ViolationType.GROSS_NEGLIGENCE: "Gross Negligence - Action or inaction which is in reckless disregard of the truth (19 U.S.C. § 1592(a)(1)(A)(ii))",
        ViolationType.FRAUD: "Fraud - Willful and intentional violation with intent to defraud the United States (19 U.S.C. § 1592(a)(1)(A)(iii))"
    }
    return descriptions.get(violation_type, "Unknown violation type")


def get_category_description(category: ViolationCategory, entry_count: int) -> str:
    """Generate violation description from category."""
    descriptions = {
        ViolationCategory.CLASSIFICATION: f"During the course of a post-entry audit, it was discovered that {entry_count} entries contained incorrect tariff classifications. The goods were classified under incorrect HTS headings, resulting in underpayment of duties.",
        ViolationCategory.VALUATION: f"A review of {entry_count} entries revealed that the declared values did not accurately reflect the transaction value of the imported merchandise, in accordance with 19 U.S.C. § 1401a.",
        ViolationCategory.COUNTRY_OF_ORIGIN: f"An audit of {entry_count} entries identified that the declared country of origin was incorrect, potentially affecting applicable duty rates and trade program eligibility.",
        ViolationCategory.MARKING: f"Review of import documentation for {entry_count} entries revealed that the country of origin marking requirements under 19 U.S.C. § 1304 were not properly satisfied.",
        ViolationCategory.ANTIDUMPING: f"Analysis of {entry_count} entries subject to antidumping/countervailing duties revealed underpayment of applicable AD/CVD duties.",
        ViolationCategory.FREE_TRADE: f"Review of {entry_count} entries claiming preferential treatment under free trade agreements identified that the goods did not qualify for the claimed preferences.",
    }
    return descriptions.get(category, f"Errors were identified in {entry_count} entries during the audit process.")


def calculate_statute_of_limitations(entry_date: str) -> Dict[str, Any]:
    """Calculate statute of limitations for an entry."""
    try:
        if isinstance(entry_date, str):
            entry_dt = datetime.strptime(entry_date[:10], "%Y-%m-%d")
        else:
            entry_dt = entry_date
        
        # 5 years for negligence/gross negligence, no limit for fraud
        expiration = entry_dt + timedelta(days=5*365)
        days_remaining = (expiration - datetime.now()).days
        
        return {
            "entry_date": entry_date[:10] if isinstance(entry_date, str) else entry_date.strftime("%Y-%m-%d"),
            "expiration_date": expiration.strftime("%Y-%m-%d"),
            "days_remaining": max(0, days_remaining),
            "expired": days_remaining <= 0
        }
    except Exception as e:
        logger.error(f"Error calculating statute: {e}")
        return {
            "entry_date": str(entry_date),
            "expiration_date": "N/A",
            "days_remaining": 0,
            "expired": True
        }


class PriorDisclosureService:
    """Service for generating prior disclosure documents."""
    
    def __init__(self, db: AsyncSession):
        self.db = db
    
    async def generate_disclosure(
        self,
        entries: List[Dict[str, Any]],
        violation_type: ViolationType = ViolationType.NEGLIGENCE,
        violation_category: ViolationCategory = ViolationCategory.CLASSIFICATION,
        importer_info: Dict[str, Any] = None,
        additional_info: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        """
        Generate a prior disclosure document.
        
        Args:
            entries: List of affected entry records
            violation_type: Type of violation (negligence, gross_negligence, fraud)
            violation_category: Category of violation
            importer_info: Importer details
            additional_info: Additional disclosure information
            
        Returns:
            Prior disclosure document with all details
        """
        importer_info = importer_info or {}
        additional_info = additional_info or {}
        
        disclosure_id = str(uuid4())[:8].upper()
        
        # Calculate totals
        total_duty_loss = sum(
            float(e.get("duty_amount", 0) or 0) * 0.1  # Estimate 10% error
            for e in entries
        )
        
        if additional_info.get("duty_loss"):
            total_duty_loss = additional_info["duty_loss"]
        
        # Calculate interest (8% per year, prorated)
        oldest_entry = min(
            (e.get("entry_date") or datetime.now().strftime("%Y-%m-%d") for e in entries),
            default=datetime.now().strftime("%Y-%m-%d")
        )
        
        if isinstance(oldest_entry, datetime):
            oldest_entry = oldest_entry.strftime("%Y-%m-%d")
        
        days_outstanding = (datetime.now() - datetime.strptime(oldest_entry[:10], "%Y-%m-%d")).days
        interest = total_duty_loss * 0.08 * (days_outstanding / 365)
        
        # Calculate penalties based on violation type
        penalty_multipliers = {
            ViolationType.NEGLIGENCE: 2,
            ViolationType.GROSS_NEGLIGENCE: 4,
            ViolationType.FRAUD: 4  # Plus domestic value cap
        }
        
        max_penalty = total_duty_loss * penalty_multipliers.get(violation_type, 2)
        mitigated_penalty = max_penalty * 0.25 * 0.75 * 0.9  # Standard reductions
        
        # Statute of limitations
        statute = calculate_statute_of_limitations(oldest_entry)
        
        # Format entry list
        entry_numbers = [e.get("entry_number", "N/A") for e in entries[:20]]
        entry_list = "\n".join([
            f"  - {e.get('entry_number', 'N/A')} ({str(e.get('entry_date', 'N/A'))[:10]})"
            for e in entries[:20]
        ])
        if len(entries) > 20:
            entry_list += f"\n  ... and {len(entries) - 20} additional entries (see attachment)"
        
        # Get ports
        ports = list(set(e.get("port_name", "Unknown") for e in entries if e.get("port_name")))
        
        # Generate disclosure text
        disclosure_text = DISCLOSURE_TEMPLATE.format(
            date=datetime.now().strftime("%B %d, %Y"),
            reference_number=f"PD-{disclosure_id}",
            importer_name=importer_info.get("name", "[IMPORTER NAME]"),
            importer_address=importer_info.get("address", "[ADDRESS]"),
            violation_category=violation_category.value.replace("_", " ").title(),
            entry_numbers=", ".join(entry_numbers[:5]) + ("..." if len(entry_numbers) > 5 else ""),
            ports=", ".join(ports) if ports else "[PORT]",
            ior_number=importer_info.get("ior_number", "[IOR NUMBER]"),
            contact_name=importer_info.get("contact", "[CONTACT NAME]"),
            contact_info=importer_info.get("email", "[EMAIL/PHONE]"),
            violation_type=violation_type.value.replace("_", " ").title(),
            violation_type_desc=get_violation_description(violation_type),
            violation_description=additional_info.get(
                "description",
                get_category_description(violation_category, len(entries))
            ),
            entry_count=len(entries),
            date_range=f"{oldest_entry} to {datetime.now().strftime('%Y-%m-%d')}",
            entry_list=entry_list,
            circumstances=additional_info.get(
                "circumstances",
                "The circumstances surrounding this violation are described below."
            ),
            audit_date=datetime.now().strftime("%Y-%m-%d"),
            discovery_details=additional_info.get(
                "discovery",
                "The violation was identified through systematic review of entry documentation and tariff classifications."
            ),
            corrective_actions=additional_info.get(
                "corrective_actions",
                "- Enhanced classification review procedures\n- Additional staff training\n- Improved documentation controls"
            ),
            duty_loss=total_duty_loss,
            interest=interest,
            total_owed=total_duty_loss + interest,
            max_penalty=max_penalty,
            mitigated_penalty=mitigated_penalty,
            tender_amount=total_duty_loss + interest,
            additional_mitigation=additional_info.get(
                "mitigation",
                "First-time disclosure for this type of violation"
            ),
            oldest_entry=oldest_entry,
            statute_expiration=statute.get("expiration_date", "N/A"),
            days_remaining=statute.get("days_remaining", "N/A"),
            attachments="- Supporting documentation\n- Entry summaries\n- Audit report",
            generated_at=datetime.now(timezone.utc).isoformat()
        )
        
        return {
            "id": disclosure_id,
            "status": "draft",
            "violation_type": violation_type.value,
            "violation_category": violation_category.value,
            "importer_name": importer_info.get("name", "Unknown"),
            "entry_count": len(entries),
            "entry_numbers": entry_numbers,
            "ports": ports,
            "total_duty_loss": round(total_duty_loss, 2),
            "estimated_interest": round(interest, 2),
            "total_owed": round(total_duty_loss + interest, 2),
            "max_penalty": round(max_penalty, 2),
            "mitigated_penalty": round(mitigated_penalty, 2),
            "potential_savings": round(max_penalty - mitigated_penalty, 2),
            "oldest_entry": oldest_entry,
            "statute_expiration": statute.get("expiration_date"),
            "days_until_expiration": statute.get("days_remaining"),
            "disclosure_text": disclosure_text,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
    
    async def get_disclosure_preview(
        self,
        duty_loss: float,
        entry_count: int = 1,
        violation_type: str = "negligence",
        oldest_entry_date: str = None
    ) -> Dict[str, Any]:
        """
        Get a quick preview of disclosure penalties without full document.
        """
        vtype = ViolationType(violation_type.lower())
        
        if oldest_entry_date is None:
            oldest_entry_date = datetime.now().strftime("%Y-%m-%d")
        
        # Calculate interest
        days = (datetime.now() - datetime.strptime(oldest_entry_date[:10], "%Y-%m-%d")).days
        interest = duty_loss * 0.08 * (days / 365)
        
        # Penalty calculation
        multipliers = {
            ViolationType.NEGLIGENCE: 2,
            ViolationType.GROSS_NEGLIGENCE: 4,
            ViolationType.FRAUD: 4
        }
        
        max_penalty = duty_loss * multipliers.get(vtype, 2)
        
        # Mitigated with prior disclosure
        mitigated = max_penalty * 0.25 * 0.75 * 0.9
        
        statute = calculate_statute_of_limitations(oldest_entry_date)
        
        return {
            "duty_loss": duty_loss,
            "entry_count": entry_count,
            "violation_type": vtype.value,
            "interest_estimate": round(interest, 2),
            "total_owed": round(duty_loss + interest, 2),
            "max_penalty": round(max_penalty, 2),
            "mitigated_penalty": round(mitigated, 2),
            "savings_with_disclosure": round(max_penalty - mitigated, 2),
            "savings_percentage": round((1 - mitigated / max_penalty) * 100, 1) if max_penalty > 0 else 0,
            "statute_expiration": statute.get("expiration_date"),
            "days_remaining": statute.get("days_remaining"),
            "urgency": "high" if statute.get("days_remaining", 0) < 180 else "normal"
        }


# Standalone functions for API

async def generate_prior_disclosure(
    db: AsyncSession,
    entries: List[Dict[str, Any]],
    violation_type: str = "negligence",
    violation_category: str = "classification",
    importer_info: Dict[str, Any] = None,
    additional_info: Dict[str, Any] = None
) -> Dict[str, Any]:
    """Generate a prior disclosure document."""
    service = PriorDisclosureService(db)
    return await service.generate_disclosure(
        entries=entries,
        violation_type=ViolationType(violation_type.lower()),
        violation_category=ViolationCategory(violation_category.lower()),
        importer_info=importer_info,
        additional_info=additional_info
    )


async def get_disclosure_preview(
    db: AsyncSession,
    duty_loss: float,
    entry_count: int = 1,
    violation_type: str = "negligence",
    oldest_entry_date: str = None
) -> Dict[str, Any]:
    """Get penalty preview for prior disclosure."""
    service = PriorDisclosureService(db)
    return await service.get_disclosure_preview(
        duty_loss=duty_loss,
        entry_count=entry_count,
        violation_type=violation_type,
        oldest_entry_date=oldest_entry_date
    )
