# Import all worker modules to ensure Celery task registration
from app.workers import (
    dispatch,
    ingest_worker,
    ingest_tasks,
    retry_worker,
    batch_runner,
    metadata_enqueue,
    process_ingest_batch,
    ingest_file_processor,
    metadata_processor,
    vectorize_worker,
    job_processor,
    agent_processor,
    key_extraction_task,
    email_monitor_worker,
    compliance_worker,
    data_fabric_worker,
    embedding_tasks,
    trade_extraction_worker,
    shipment_assembly_worker,
)

__all__ = [
    "dispatch",
    "ingest_worker",
    "ingest_tasks",
    "retry_worker",
    "batch_runner",
    "metadata_enqueue",
    "process_ingest_batch",
    "ingest_file_processor",
    "metadata_processor",
    "vectorize_worker",
    "job_processor",
    "agent_processor",
    "key_extraction_task",
    "email_monitor_worker",
    "compliance_worker",
    "data_fabric_worker",
    "embedding_tasks",
    "trade_extraction_worker",
    "shipment_assembly_worker",
]

