"""add_api_keys_notifications_webhooks

Revision ID: 549bf051bec7
Revises: g3h4i5j6k7l8
Create Date: 2026-02-07 16:00:40.444401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549bf051bec7'
down_revision: Union[str, None] = 'g3h4i5j6k7l8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_licenses',
    sa.Column('license_number', sa.String(length=20), nullable=False),
    sa.Column('filer_code', sa.String(length=10), nullable=True),
    sa.Column('broker_name', sa.String(length=500), nullable=False),
    sa.Column('broker_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('last_renewal_date', sa.Date(), nullable=True),
    sa.Column('issuing_district', sa.String(length=10), nullable=True),
    sa.Column('permitted_ports', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('primary_contact', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('exam_pass_date', sa.Date(), nullable=True),
    sa.Column('triennial_status_report_due', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broker_licenses_expiration', 'broker_licenses', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_broker_licenses_filer_code'), 'broker_licenses', ['filer_code'], unique=False)
    op.create_index(op.f('ix_broker_licenses_license_number'), 'broker_licenses', ['license_number'], unique=True)
    op.create_index('ix_broker_licenses_status', 'broker_licenses', ['status'], unique=False)
    op.create_table('broker_port_permits',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('port_code', sa.String(length=10), nullable=False),
    sa.Column('port_name', sa.String(length=100), nullable=True),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['broker_licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broker_port_permits_license', 'broker_port_permits', ['license_id'], unique=False)
    op.create_index('ix_broker_port_permits_port', 'broker_port_permits', ['port_code'], unique=False)
    op.create_index(op.f('ix_broker_port_permits_port_code'), 'broker_port_permits', ['port_code'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('max_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('rate_limit_tier', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['client_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['client_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_bonds',
    sa.Column('bond_number', sa.String(length=50), nullable=False),
    sa.Column('bond_type', sa.String(length=30), nullable=False),
    sa.Column('activity_code', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('surety_code', sa.String(length=10), nullable=True),
    sa.Column('surety_name', sa.String(length=200), nullable=True),
    sa.Column('bond_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('license_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('principal_name', sa.String(length=500), nullable=True),
    sa.Column('principal_ior_number', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('entry_id', sa.UUID(), nullable=True),
    sa.Column('entry_number', sa.String(length=20), nullable=True),
    sa.Column('covered_ports', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rider_count', sa.Integer(), nullable=True),
    sa.Column('last_rider_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['broker_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_bonds_bond_number'), 'broker_bonds', ['bond_number'], unique=True)
    op.create_index('ix_broker_bonds_client', 'broker_bonds', ['client_id'], unique=False)
    op.create_index('ix_broker_bonds_expiration', 'broker_bonds', ['expiration_date'], unique=False)
    op.create_index('ix_broker_bonds_status', 'broker_bonds', ['status'], unique=False)
    op.create_index('ix_broker_bonds_surety', 'broker_bonds', ['surety_code'], unique=False)
    op.create_index(op.f('ix_broker_bonds_surety_code'), 'broker_bonds', ['surety_code'], unique=False)
    op.create_index('ix_broker_bonds_type', 'broker_bonds', ['bond_type'], unique=False)
    op.drop_index('idx_lpe_created', table_name='landing_page_events')
    op.drop_index('idx_lpe_session', table_name='landing_page_events')
    op.drop_index('idx_lpe_type', table_name='landing_page_events')
    op.drop_table('landing_page_events')
    op.drop_index('idx_leads_email', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_user_role_organization_id', table_name='user_roles')
    op.drop_index('idx_user_role_role_id', table_name='user_roles')
    op.drop_index('idx_user_role_user_id', table_name='user_roles')
    op.drop_index('idx_user_role_user_org', table_name='user_roles')
    op.drop_table('user_roles')
    op.alter_column('ace_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ace_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('billable_items', sa.Column('fee_config_id', sa.UUID(), nullable=True))
    op.add_column('billable_items', sa.Column('is_invoiced', sa.Boolean(), nullable=False))
    op.add_column('billable_items', sa.Column('invoiced_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('billable_items', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('billable_items', 'item_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'entry'::character varying"))
    op.alter_column('billable_items', 'reference_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('billable_items', 'service_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('billable_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('billable_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('billable_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('billable_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billable_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_billable_items_client', 'billable_items', ['client_id'], unique=False)
    op.create_index('ix_billable_items_invoice', 'billable_items', ['invoice_id'], unique=False)
    op.create_index('ix_billable_items_invoiced', 'billable_items', ['is_invoiced'], unique=False)
    op.create_index('ix_billable_items_service_date', 'billable_items', ['service_date'], unique=False)
    op.create_index('ix_billable_items_type', 'billable_items', ['item_type'], unique=False)
    op.create_foreign_key(None, 'billable_items', 'client_fee_configs', ['fee_config_id'], ['id'])
    op.drop_column('billable_items', 'is_billed')
    op.drop_index('ix_client_bonds_active', table_name='client_bonds')
    op.drop_index('ix_client_bonds_client', table_name='client_bonds')
    op.drop_index('ix_client_bonds_number', table_name='client_bonds')
    op.drop_index('ix_client_contacts_client', table_name='client_contacts')
    op.drop_index('ix_client_contacts_email', table_name='client_contacts')
    op.alter_column('client_fee_configs', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_fee_configs', 'fee_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'flat'::character varying"))
    op.alter_column('client_fee_configs', 'billable_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'entry'::character varying"))
    op.alter_column('client_fee_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('client_fee_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_fee_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_client_fee_configs_client', 'client_fee_configs', ['client_id'], unique=False)
    op.create_index('ix_client_fee_configs_type', 'client_fee_configs', ['billable_type'], unique=False)
    op.alter_column('client_invoices', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_invoices', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('client_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('client_invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'payment_reference',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('client_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_client_invoices_client', 'client_invoices', ['client_id'], unique=False)
    op.create_index('ix_client_invoices_date', 'client_invoices', ['invoice_date'], unique=False)
    op.create_index('ix_client_invoices_due', 'client_invoices', ['due_date'], unique=False)
    op.create_index('ix_client_invoices_status', 'client_invoices', ['status'], unique=False)
    op.drop_column('client_invoices', 'paid_at')
    op.alter_column('client_notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_notifications', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('client_notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('client_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_client_notifications_client', 'client_notifications', ['client_id'], unique=False)
    op.create_index('ix_client_notifications_read', 'client_notifications', ['is_read'], unique=False)
    op.create_index('ix_client_notifications_type', 'client_notifications', ['notification_type'], unique=False)
    op.create_index('ix_client_notifications_user', 'client_notifications', ['user_id'], unique=False)
    op.drop_index('ix_client_settings_client', table_name='client_settings')
    op.alter_column('client_user_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('client_user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_user_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('client_user_sessions_token_key', 'client_user_sessions', type_='unique')
    op.create_index('ix_client_user_sessions_active', 'client_user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_client_user_sessions_token'), 'client_user_sessions', ['token'], unique=True)
    op.create_index('ix_client_user_sessions_user', 'client_user_sessions', ['user_id'], unique=False)
    op.alter_column('client_users', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_users', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('client_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('client_users_email_key', 'client_users', type_='unique')
    op.create_index('ix_client_users_client', 'client_users', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_index('ix_client_users_status', 'client_users', ['status'], unique=False)
    op.alter_column('document_metadata', 'compliance_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_metadata', 'agent_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('document_requests', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('document_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_document_requests_client', 'document_requests', ['client_id'], unique=False)
    op.create_index('ix_document_requests_due', 'document_requests', ['due_date'], unique=False)
    op.create_index('ix_document_requests_entry', 'document_requests', ['entry_id'], unique=False)
    op.create_index('ix_document_requests_status', 'document_requests', ['status'], unique=False)
    op.create_foreign_key(None, 'document_requests', 'entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.alter_column('drawback_claims', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('drawback_claims', 'import_entry_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('drawback_claims', 'import_entry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('drawback_claims', 'cbp_witnessed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('drawback_claims', 'drawback_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('99.0'))
    op.alter_column('drawback_claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('drawback_claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('drawback_claims_claim_number_key', 'drawback_claims', type_='unique')
    op.create_index(op.f('ix_drawback_claims_claim_number'), 'drawback_claims', ['claim_number'], unique=True)
    op.create_index('ix_drawback_claims_client', 'drawback_claims', ['client_id'], unique=False)
    op.create_index('ix_drawback_claims_status', 'drawback_claims', ['status'], unique=False)
    op.create_index('ix_drawback_claims_type', 'drawback_claims', ['drawback_type'], unique=False)
    op.drop_index('ix_entries_source_type', table_name='entries')
    op.alter_column('entry_liquidations', 'entry_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('entry_liquidations', 'extension_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('entry_liquidations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_liquidations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_entry_liquidations_deadline', 'entry_liquidations', ['current_deadline'], unique=False)
    op.create_index('ix_entry_liquidations_entry', 'entry_liquidations', ['entry_id'], unique=False)
    op.create_index('ix_entry_liquidations_status', 'entry_liquidations', ['status'], unique=False)
    op.alter_column('entry_protests', 'entry_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('entry_protests', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('entry_protests', 'escalated_to_cit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('entry_protests', 'supporting_documents',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('entry_protests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_protests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('entry_protests_protest_number_key', 'entry_protests', type_='unique')
    op.create_index('ix_entry_protests_client', 'entry_protests', ['client_id'], unique=False)
    op.create_index('ix_entry_protests_deadline', 'entry_protests', ['filing_deadline'], unique=False)
    op.create_index('ix_entry_protests_entry', 'entry_protests', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_protests_protest_number'), 'entry_protests', ['protest_number'], unique=True)
    op.create_index('ix_entry_protests_status', 'entry_protests', ['status'], unique=False)
    op.alter_column('generated_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('generated_reports', 'recipients',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('generated_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_generated_reports_schedule', 'generated_reports', ['schedule_id'], unique=False)
    op.create_index('ix_generated_reports_status', 'generated_reports', ['status'], unique=False)
    op.create_index('ix_generated_reports_type', 'generated_reports', ['report_type'], unique=False)
    op.alter_column('help_articles', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('help_articles', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('help_articles', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('help_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('help_articles_slug_key', 'help_articles', type_='unique')
    op.create_index(op.f('ix_help_articles_category'), 'help_articles', ['category'], unique=False)
    op.create_index('ix_help_articles_published', 'help_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_help_articles_slug'), 'help_articles', ['slug'], unique=True)
    op.drop_index('hts_codes_embedding_idx', table_name='hts_codes', postgresql_using='hnsw')
    op.drop_index('idx_hts_codes_chapter', table_name='hts_codes')
    op.drop_index('idx_hts_codes_code', table_name='hts_codes')
    op.create_index(op.f('ix_hts_codes_hts_code'), 'hts_codes', ['hts_code'], unique=True)
    op.alter_column('invoice_payments', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoice_payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('invoice_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_invoice_payments_date', 'invoice_payments', ['payment_date'], unique=False)
    op.create_index('ix_invoice_payments_invoice', 'invoice_payments', ['invoice_id'], unique=False)
    op.alter_column('isf_amendments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('isf_amendments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_isf_amendments_isf_id', 'isf_amendments', ['isf_id'], unique=False)
    op.alter_column('isf_filings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('isf_filings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('isf_filings_isf_number_key', 'isf_filings', type_='unique')
    op.create_index('ix_isf_filings_entry', 'isf_filings', ['entry_id'], unique=False)
    op.create_index('ix_isf_filings_importer', 'isf_filings', ['importer_of_record_number'], unique=False)
    op.create_index(op.f('ix_isf_filings_importer_of_record_number'), 'isf_filings', ['importer_of_record_number'], unique=False)
    op.create_index(op.f('ix_isf_filings_isf_number'), 'isf_filings', ['isf_number'], unique=True)
    op.create_index('ix_isf_filings_shipment', 'isf_filings', ['shipment_id'], unique=False)
    op.create_index('ix_isf_filings_status', 'isf_filings', ['status'], unique=False)
    op.create_index('ix_isf_filings_vessel', 'isf_filings', ['vessel_name', 'voyage_number'], unique=False)
    op.create_foreign_key(None, 'isf_filings', 'entries', ['entry_id'], ['id'])
    op.create_foreign_key(None, 'isf_filings', 'shipments', ['shipment_id'], ['id'])
    op.drop_index('idx_naics_codes_code', table_name='naics_codes')
    op.drop_index('idx_naics_sector', table_name='naics_codes')
    op.drop_index('naics_codes_embedding_idx', table_name='naics_codes', postgresql_using='hnsw')
    op.create_index(op.f('ix_naics_codes_code'), 'naics_codes', ['code'], unique=True)
    op.drop_index('idx_ofac_active', table_name='ofac_sdn')
    op.drop_index('idx_ofac_program', table_name='ofac_sdn')
    op.drop_index('idx_ofac_sdn_name', table_name='ofac_sdn')
    op.drop_index('ofac_sdn_embedding_idx', table_name='ofac_sdn', postgresql_using='hnsw')
    op.create_index(op.f('ix_ofac_sdn_sdn_name'), 'ofac_sdn', ['sdn_name'], unique=False)
    op.alter_column('onboarding_progress', 'current_step',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'welcome'::character varying"))
    op.alter_column('onboarding_progress', 'welcome_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'company_profile_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'ace_credentials_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'first_client_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'upload_document_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'create_entry_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'is_skipped',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('onboarding_progress_user_id_key', 'onboarding_progress', type_='unique')
    op.create_index(op.f('ix_onboarding_progress_user_id'), 'onboarding_progress', ['user_id'], unique=True)
    op.create_index('ix_onboarding_status', 'onboarding_progress', ['is_completed'], unique=False)
    op.create_index('ix_onboarding_user', 'onboarding_progress', ['user_id'], unique=False)
    op.alter_column('organization_subscriptions', 'tier',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organization_subscriptions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'trialing'::character varying"))
    op.alter_column('organization_subscriptions', 'entries_this_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('organization_subscriptions', 'entries_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('organization_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('organization_subscriptions_organization_id_key', 'organization_subscriptions', type_='unique')
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=True)
    op.create_index('ix_subscriptions_org', 'organization_subscriptions', ['organization_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'organization_subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_tier', 'organization_subscriptions', ['tier'], unique=False)
    op.alter_column('portal_invitations', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('portal_invitations', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'readonly'::character varying"))
    op.alter_column('portal_invitations', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('portal_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('portal_invitations_token_key', 'portal_invitations', type_='unique')
    op.create_index('ix_portal_invitations_client', 'portal_invitations', ['client_id'], unique=False)
    op.create_index(op.f('ix_portal_invitations_email'), 'portal_invitations', ['email'], unique=False)
    op.create_index('ix_portal_invitations_status', 'portal_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_portal_invitations_token'), 'portal_invitations', ['token'], unique=True)
    op.alter_column('prior_disclosures', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('prior_disclosures', 'affected_entry_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('prior_disclosures', 'entry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('prior_disclosures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prior_disclosures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('prior_disclosures_disclosure_number_key', 'prior_disclosures', type_='unique')
    op.create_index('ix_prior_disclosures_client', 'prior_disclosures', ['client_id'], unique=False)
    op.create_index(op.f('ix_prior_disclosures_disclosure_number'), 'prior_disclosures', ['disclosure_number'], unique=True)
    op.create_index('ix_prior_disclosures_status', 'prior_disclosures', ['status'], unique=False)
    op.alter_column('reconciliation_entries', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reconciliation_entries', 'flag_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reconciliation_entries', 'flagged_entry_ids',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reconciliation_entries', 'entry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('reconciliation_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reconciliation_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('reconciliation_entries_recon_entry_number_key', 'reconciliation_entries', type_='unique')
    op.create_index('ix_reconciliation_entries_client', 'reconciliation_entries', ['client_id'], unique=False)
    op.create_index('ix_reconciliation_entries_deadline', 'reconciliation_entries', ['filing_deadline'], unique=False)
    op.create_index(op.f('ix_reconciliation_entries_recon_entry_number'), 'reconciliation_entries', ['recon_entry_number'], unique=True)
    op.create_index('ix_reconciliation_entries_status', 'reconciliation_entries', ['status'], unique=False)
    op.drop_index('idx_review_queue_priority', table_name='review_queue')
    op.create_index('idx_review_queue_priority', 'review_queue', ['priority'], unique=False, postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    op.alter_column('scheduled_reports', 'recipients',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('scheduled_reports', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduled_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_scheduled_reports_active', 'scheduled_reports', ['is_active'], unique=False)
    op.create_index('ix_scheduled_reports_next_run', 'scheduled_reports', ['next_run_at'], unique=False)
    op.create_index('ix_scheduled_reports_type', 'scheduled_reports', ['report_type'], unique=False)
    op.alter_column('security_audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.alter_column('security_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_audit_log_action', 'security_audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_resource', 'security_audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_log_time', 'security_audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_user', 'security_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_action'), 'security_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_security_audit_log_resource_type'), 'security_audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_security_audit_log_user_id'), 'security_audit_log', ['user_id'], unique=False)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'document_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('ix_shipments_status', 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shipments_status', table_name='shipments')
    op.alter_column('shipments', 'document_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_security_audit_log_user_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_resource_type'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_action'), table_name='security_audit_log')
    op.drop_index('ix_audit_log_user', table_name='security_audit_log')
    op.drop_index('ix_audit_log_time', table_name='security_audit_log')
    op.drop_index('ix_audit_log_resource', table_name='security_audit_log')
    op.drop_index('ix_audit_log_action', table_name='security_audit_log')
    op.alter_column('security_audit_log', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('security_audit_log', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_index('ix_scheduled_reports_type', table_name='scheduled_reports')
    op.drop_index('ix_scheduled_reports_next_run', table_name='scheduled_reports')
    op.drop_index('ix_scheduled_reports_active', table_name='scheduled_reports')
    op.alter_column('scheduled_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scheduled_reports', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('scheduled_reports', 'recipients',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index('idx_review_queue_priority', table_name='review_queue', postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_review_queue_priority', 'review_queue', [sa.text('priority DESC')], unique=False)
    op.drop_index('ix_reconciliation_entries_status', table_name='reconciliation_entries')
    op.drop_index(op.f('ix_reconciliation_entries_recon_entry_number'), table_name='reconciliation_entries')
    op.drop_index('ix_reconciliation_entries_deadline', table_name='reconciliation_entries')
    op.drop_index('ix_reconciliation_entries_client', table_name='reconciliation_entries')
    op.create_unique_constraint('reconciliation_entries_recon_entry_number_key', 'reconciliation_entries', ['recon_entry_number'])
    op.alter_column('reconciliation_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reconciliation_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('reconciliation_entries', 'entry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('reconciliation_entries', 'flagged_entry_ids',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reconciliation_entries', 'flag_types',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reconciliation_entries', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_prior_disclosures_status', table_name='prior_disclosures')
    op.drop_index(op.f('ix_prior_disclosures_disclosure_number'), table_name='prior_disclosures')
    op.drop_index('ix_prior_disclosures_client', table_name='prior_disclosures')
    op.create_unique_constraint('prior_disclosures_disclosure_number_key', 'prior_disclosures', ['disclosure_number'])
    op.alter_column('prior_disclosures', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prior_disclosures', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prior_disclosures', 'entry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('prior_disclosures', 'affected_entry_ids',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('prior_disclosures', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_portal_invitations_token'), table_name='portal_invitations')
    op.drop_index('ix_portal_invitations_status', table_name='portal_invitations')
    op.drop_index(op.f('ix_portal_invitations_email'), table_name='portal_invitations')
    op.drop_index('ix_portal_invitations_client', table_name='portal_invitations')
    op.create_unique_constraint('portal_invitations_token_key', 'portal_invitations', ['token'])
    op.alter_column('portal_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('portal_invitations', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('portal_invitations', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'readonly'::character varying"))
    op.alter_column('portal_invitations', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_subscriptions_tier', table_name='organization_subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='organization_subscriptions')
    op.drop_index('ix_subscriptions_org', table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.create_unique_constraint('organization_subscriptions_organization_id_key', 'organization_subscriptions', ['organization_id'])
    op.alter_column('organization_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_subscriptions', 'entries_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('organization_subscriptions', 'entries_this_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('organization_subscriptions', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'trialing'::character varying"))
    op.alter_column('organization_subscriptions', 'tier',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.drop_index('ix_onboarding_user', table_name='onboarding_progress')
    op.drop_index('ix_onboarding_status', table_name='onboarding_progress')
    op.drop_index(op.f('ix_onboarding_progress_user_id'), table_name='onboarding_progress')
    op.create_unique_constraint('onboarding_progress_user_id_key', 'onboarding_progress', ['user_id'])
    op.alter_column('onboarding_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_progress', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('onboarding_progress', 'is_skipped',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'create_entry_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'upload_document_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'first_client_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'ace_credentials_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'company_profile_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'welcome_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('onboarding_progress', 'current_step',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'welcome'::character varying"))
    op.drop_index(op.f('ix_ofac_sdn_sdn_name'), table_name='ofac_sdn')
    op.create_index('ofac_sdn_embedding_idx', 'ofac_sdn', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('idx_ofac_sdn_name', 'ofac_sdn', ['sdn_name'], unique=False)
    op.create_index('idx_ofac_program', 'ofac_sdn', ['program'], unique=False)
    op.create_index('idx_ofac_active', 'ofac_sdn', ['is_active'], unique=False)
    op.drop_index(op.f('ix_naics_codes_code'), table_name='naics_codes')
    op.create_index('naics_codes_embedding_idx', 'naics_codes', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_index('idx_naics_sector', 'naics_codes', ['sector'], unique=False)
    op.create_index('idx_naics_codes_code', 'naics_codes', ['code'], unique=False)
    op.drop_constraint(None, 'isf_filings', type_='foreignkey')
    op.drop_constraint(None, 'isf_filings', type_='foreignkey')
    op.drop_index('ix_isf_filings_vessel', table_name='isf_filings')
    op.drop_index('ix_isf_filings_status', table_name='isf_filings')
    op.drop_index('ix_isf_filings_shipment', table_name='isf_filings')
    op.drop_index(op.f('ix_isf_filings_isf_number'), table_name='isf_filings')
    op.drop_index(op.f('ix_isf_filings_importer_of_record_number'), table_name='isf_filings')
    op.drop_index('ix_isf_filings_importer', table_name='isf_filings')
    op.drop_index('ix_isf_filings_entry', table_name='isf_filings')
    op.create_unique_constraint('isf_filings_isf_number_key', 'isf_filings', ['isf_number'])
    op.alter_column('isf_filings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('isf_filings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_isf_amendments_isf_id', table_name='isf_amendments')
    op.alter_column('isf_amendments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('isf_amendments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_invoice_payments_invoice', table_name='invoice_payments')
    op.drop_index('ix_invoice_payments_date', table_name='invoice_payments')
    op.alter_column('invoice_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoice_payments', 'payment_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('invoice_payments', 'invoice_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_hts_codes_hts_code'), table_name='hts_codes')
    op.create_index('idx_hts_codes_code', 'hts_codes', ['hts_code'], unique=False)
    op.create_index('idx_hts_codes_chapter', 'hts_codes', ['chapter'], unique=False)
    op.create_index('hts_codes_embedding_idx', 'hts_codes', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_help_articles_slug'), table_name='help_articles')
    op.drop_index('ix_help_articles_published', table_name='help_articles')
    op.drop_index(op.f('ix_help_articles_category'), table_name='help_articles')
    op.create_unique_constraint('help_articles_slug_key', 'help_articles', ['slug'])
    op.alter_column('help_articles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('help_articles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('help_articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('help_articles', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('help_articles', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('help_articles', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_generated_reports_type', table_name='generated_reports')
    op.drop_index('ix_generated_reports_status', table_name='generated_reports')
    op.drop_index('ix_generated_reports_schedule', table_name='generated_reports')
    op.alter_column('generated_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_reports', 'recipients',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('generated_reports', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_entry_protests_status', table_name='entry_protests')
    op.drop_index(op.f('ix_entry_protests_protest_number'), table_name='entry_protests')
    op.drop_index('ix_entry_protests_entry', table_name='entry_protests')
    op.drop_index('ix_entry_protests_deadline', table_name='entry_protests')
    op.drop_index('ix_entry_protests_client', table_name='entry_protests')
    op.create_unique_constraint('entry_protests_protest_number_key', 'entry_protests', ['protest_number'])
    op.alter_column('entry_protests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_protests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_protests', 'supporting_documents',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('entry_protests', 'escalated_to_cit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('entry_protests', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('entry_protests', 'entry_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_entry_liquidations_status', table_name='entry_liquidations')
    op.drop_index('ix_entry_liquidations_entry', table_name='entry_liquidations')
    op.drop_index('ix_entry_liquidations_deadline', table_name='entry_liquidations')
    op.alter_column('entry_liquidations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_liquidations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entry_liquidations', 'extension_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('entry_liquidations', 'entry_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_entries_source_type', 'entries', ['source_type'], unique=False)
    op.drop_index('ix_drawback_claims_type', table_name='drawback_claims')
    op.drop_index('ix_drawback_claims_status', table_name='drawback_claims')
    op.drop_index('ix_drawback_claims_client', table_name='drawback_claims')
    op.drop_index(op.f('ix_drawback_claims_claim_number'), table_name='drawback_claims')
    op.create_unique_constraint('drawback_claims_claim_number_key', 'drawback_claims', ['claim_number'])
    op.alter_column('drawback_claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drawback_claims', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('drawback_claims', 'drawback_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('99.0'))
    op.alter_column('drawback_claims', 'cbp_witnessed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('drawback_claims', 'import_entry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('drawback_claims', 'import_entry_ids',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('drawback_claims', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'document_requests', type_='foreignkey')
    op.drop_index('ix_document_requests_status', table_name='document_requests')
    op.drop_index('ix_document_requests_entry', table_name='document_requests')
    op.drop_index('ix_document_requests_due', table_name='document_requests')
    op.drop_index('ix_document_requests_client', table_name='document_requests')
    op.alter_column('document_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_requests', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('document_metadata', 'agent_results',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_metadata', 'compliance_results',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_client_users_status', table_name='client_users')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_index('ix_client_users_client', table_name='client_users')
    op.create_unique_constraint('client_users_email_key', 'client_users', ['email'])
    op.alter_column('client_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_users', 'login_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_users', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_client_user_sessions_user', table_name='client_user_sessions')
    op.drop_index(op.f('ix_client_user_sessions_token'), table_name='client_user_sessions')
    op.drop_index('ix_client_user_sessions_active', table_name='client_user_sessions')
    op.create_unique_constraint('client_user_sessions_token_key', 'client_user_sessions', ['token'])
    op.alter_column('client_user_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_user_sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('client_user_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_client_settings_client', 'client_settings', ['client_id'], unique=False)
    op.drop_index('ix_client_notifications_user', table_name='client_notifications')
    op.drop_index('ix_client_notifications_type', table_name='client_notifications')
    op.drop_index('ix_client_notifications_read', table_name='client_notifications')
    op.drop_index('ix_client_notifications_client', table_name='client_notifications')
    op.alter_column('client_notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_notifications', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('client_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('client_notifications', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('client_notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('client_invoices', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('ix_client_invoices_status', table_name='client_invoices')
    op.drop_index('ix_client_invoices_due', table_name='client_invoices')
    op.drop_index('ix_client_invoices_date', table_name='client_invoices')
    op.drop_index('ix_client_invoices_client', table_name='client_invoices')
    op.alter_column('client_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_invoices', 'payment_reference',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('client_invoices', 'amount_due',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'amount_paid',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'discount_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('client_invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('client_invoices', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('client_invoices', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_client_fee_configs_type', table_name='client_fee_configs')
    op.drop_index('ix_client_fee_configs_client', table_name='client_fee_configs')
    op.alter_column('client_fee_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_fee_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_fee_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('client_fee_configs', 'billable_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'entry'::character varying"))
    op.alter_column('client_fee_configs', 'fee_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'flat'::character varying"))
    op.alter_column('client_fee_configs', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_client_contacts_email', 'client_contacts', ['email'], unique=False)
    op.create_index('ix_client_contacts_client', 'client_contacts', ['client_id'], unique=False)
    op.create_index('ix_client_bonds_number', 'client_bonds', ['bond_number'], unique=False)
    op.create_index('ix_client_bonds_client', 'client_bonds', ['client_id'], unique=False)
    op.create_index('ix_client_bonds_active', 'client_bonds', ['is_active'], unique=False)
    op.add_column('billable_items', sa.Column('is_billed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billable_items', type_='foreignkey')
    op.drop_index('ix_billable_items_type', table_name='billable_items')
    op.drop_index('ix_billable_items_service_date', table_name='billable_items')
    op.drop_index('ix_billable_items_invoiced', table_name='billable_items')
    op.drop_index('ix_billable_items_invoice', table_name='billable_items')
    op.drop_index('ix_billable_items_client', table_name='billable_items')
    op.alter_column('billable_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billable_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billable_items', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('billable_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    op.alter_column('billable_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('billable_items', 'service_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('billable_items', 'reference_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('billable_items', 'item_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'entry'::character varying"))
    op.alter_column('billable_items', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('billable_items', 'invoiced_at')
    op.drop_column('billable_items', 'is_invoiced')
    op.drop_column('billable_items', 'fee_config_id')
    op.alter_column('ace_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ace_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('user_roles',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='user_roles_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey'),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id', name='uq_user_role_org')
    )
    op.create_index('idx_user_role_user_org', 'user_roles', ['user_id', 'organization_id'], unique=False)
    op.create_index('idx_user_role_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('idx_user_role_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_role_organization_id', 'user_roles', ['organization_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('company_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'new'::character varying"), autoincrement=False, nullable=True),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='leads_pkey'),
    sa.UniqueConstraint('email', name='leads_email_key')
    )
    op.create_index('idx_leads_email', 'leads', ['email'], unique=False)
    op.create_table('landing_page_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('page_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('element_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('utm_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('utm_medium', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('utm_campaign', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('event_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='landing_page_events_pkey')
    )
    op.create_index('idx_lpe_type', 'landing_page_events', ['event_type'], unique=False)
    op.create_index('idx_lpe_session', 'landing_page_events', ['session_id'], unique=False)
    op.create_index('idx_lpe_created', 'landing_page_events', ['created_at'], unique=False)
    op.drop_index('ix_broker_bonds_type', table_name='broker_bonds')
    op.drop_index(op.f('ix_broker_bonds_surety_code'), table_name='broker_bonds')
    op.drop_index('ix_broker_bonds_surety', table_name='broker_bonds')
    op.drop_index('ix_broker_bonds_status', table_name='broker_bonds')
    op.drop_index('ix_broker_bonds_expiration', table_name='broker_bonds')
    op.drop_index('ix_broker_bonds_client', table_name='broker_bonds')
    op.drop_index(op.f('ix_broker_bonds_bond_number'), table_name='broker_bonds')
    op.drop_table('broker_bonds')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('api_keys')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_broker_port_permits_port_code'), table_name='broker_port_permits')
    op.drop_index('ix_broker_port_permits_port', table_name='broker_port_permits')
    op.drop_index('ix_broker_port_permits_license', table_name='broker_port_permits')
    op.drop_table('broker_port_permits')
    op.drop_index('ix_broker_licenses_status', table_name='broker_licenses')
    op.drop_index(op.f('ix_broker_licenses_license_number'), table_name='broker_licenses')
    op.drop_index(op.f('ix_broker_licenses_filer_code'), table_name='broker_licenses')
    op.drop_index('ix_broker_licenses_expiration', table_name='broker_licenses')
    op.drop_table('broker_licenses')
    # ### end Alembic commands ###
