"""add_api_keys_notifications_webhooks

Revision ID: 6ba76a0b6501
Revises: 549bf051bec7
Create Date: 2026-02-07 16:01:03.690378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba76a0b6501'
down_revision: Union[str, None] = '549bf051bec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_queue_priority', table_name='review_queue')
    op.create_index('idx_review_queue_priority', 'review_queue', ['priority'], unique=False, postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_queue_priority', table_name='review_queue', postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_review_queue_priority', 'review_queue', [sa.text('priority DESC')], unique=False)
    # ### end Alembic commands ###
