"""Add_Silver_and_Gold_Data_Layers

Revision ID: b663ab8dfc32
Revises: 
Create Date: 2026-01-23 05:03:27.076311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b663ab8dfc32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_role_organization_id', table_name='user_roles')
    op.drop_index('idx_user_role_role_id', table_name='user_roles')
    op.drop_index('idx_user_role_user_id', table_name='user_roles')
    op.drop_index('idx_user_role_user_org', table_name='user_roles')
    op.drop_table('user_roles')
    op.alter_column('correction_logs', 'used_for_training',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('extraction_results', 'page_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('idx_review_queue_priority', table_name='review_queue')
    op.create_index('idx_review_queue_priority', 'review_queue', ['priority'], unique=False, postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_queue_priority', table_name='review_queue', postgresql_using='btree', postgresql_ops={'priority': 'DESC'})
    op.create_index('idx_review_queue_priority', 'review_queue', [sa.text('priority DESC')], unique=False)
    op.alter_column('extraction_results', 'page_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('correction_logs', 'used_for_training',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='user_roles_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_roles_pkey'),
    sa.UniqueConstraint('user_id', 'role_id', 'organization_id', name='uq_user_role_org')
    )
    op.create_index('idx_user_role_user_org', 'user_roles', ['user_id', 'organization_id'], unique=False)
    op.create_index('idx_user_role_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('idx_user_role_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_role_organization_id', 'user_roles', ['organization_id'], unique=False)
    # ### end Alembic commands ###
